        <div class="d-flex flex-column justify-content-center align-items-center" style="height:100vh">
            <div class="container-fluid text-center mt-5">
                <img src="<?=$this->url('img/divak.png'); ?>"  alt="Divak Framework" style="width:40%"/>
            </div>
            <div class="container-fluid bg-light p-5 rounded-lg mt-5 text-center">
                <h1>Welcome to <br /><span class="text-info">Divak</span> Framework</h1>
            </div>
            <div class="container-fluid alert alert-info text-center mb-5">
                <?php $this->_('Easiest way in building modern site');?>
            </div>
        </div>