<!DOCTYPE HTML>
<html lang="<?php echo $this->lang;?>">
<head>
<title>Page Error - <?php echo $this->title();?></title>                                                  
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style>
    *{padding:0;margin:0;}
    body{font-family: Helvetica,Arial,sans-serif;font-size:12px;background:#fff;}
    a:link,a:visited{color: #0398CA;}
    h1{font-size:24px;}
    h3{font-size:18px;}
    .info{text-align:center;margin-top:15%;}
    .info .more-information{padding:20px;}
    .err-box{max-width:800px;padding: 4% 30px;margin:0 auto;border:2px solid #D6154B;background: #fff,-webkit-box-shadow: 0px 2px 25px 0px rgba(252,104,141,1);-moz-box-shadow: 0px 2px 25px 0px rgba(252,104,141,1);box-shadow: 0px 2px 25px 0px rgba(252,104,141,1);}
    .pre{font-family: verdana;text-align: left;}
</style>  
</head>
<body class="body">
    <div class="info">
        <?php if (\Config::get('app.show_errors')) {?>
           <div class="err-box"><p class="pre"><?php echo $description ?></p></div>
        <?php } else { ?>
           <h3><?php echo $description ?></h3> 
           <div class="more-information">
                <p>
                    <a href="<?php $this->url();?>"><?php $this->_('Return to home page');?></a>
                </p>
           </div>  
        <?php } ?>
    </div>
</body>
</html>