<!DOCTYPE html>
<html lang="<?php echo $this->lang ;?>">
<head>
	<title><?php echo $this->title(); ?></title>
	<meta charset="utf-8" /> 
	<meta http-equiv="cache-control" content="no-cache" />
	<meta http-equiv="expires" content="0"/>
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
	<meta http-equiv="X-UA-Compatible"  content="IE=edge, chrome=1" /> 
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta name="description" content=""/>
	<link href="<?php $this->url('favicon.ico'); ?>" rel="icon" />
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous" />
	<link rel="stylesheet" href="<? $this->url('css/style.css'); ?>" type="text/css" />
</head>
<body>
	<div class="container">
		<header></header>
		<div class="content">
			<?php $this->getContent(); ?>
		</div>
		<footer></footer>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script type="text/javascript" src="<?php $this->url('js/script.js'); ?>"></script>
	</div>
</body>
</html>