<!DOCTYPE html>
<html lang="<?=$this->lang ;?>">
<head>
	<title><?=$this->title(); ?></title>
	<meta charset="utf-8" /> 
	<meta http-equiv="cache-control" content="no-cache" />
	<meta http-equiv="expires" content="0"/>
	<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
	<meta http-equiv="pragma" content="no-cache" />
	<meta http-equiv="X-UA-Compatible"  content="IE=edge, chrome=1" /> 
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta name="description" content=""/>
	<link href="<?php $this->url('favicon.ico'); ?>" rel="icon" />
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
	<link rel="stylesheet" href="<?php $this->url('css/style.css'); ?>" type="text/css" />
</head>
<body>
	<div class="container">
		<header></header>

		<div class="content">
			<?php $this->getContent(); ?>
		</div>

		<footer></footer>

		<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
		<script type="text/javascript" src="<?php $this->url('js/script.js'); ?>"></script>
	</div>
</body>
</html>
